var ww=$(window).width();$(document).ready(function(){filtertabs(1);});(function($){$.fn.hasScrollBar=function(){return this.get(0).scrollWidth>this.width();}})(jQuery);if($("#allexams-row-scroll").length){var scrollres=$("#allexams-row-scroll").hasScrollBar();if(ww>=992){if(scrollres){$("#allexams-tabarrows-right").css("display","flex");}else{$("#allexams-tabarrows-right").hide();$("#allexams-row-scroll").parent(".sec-scroll-group").css("padding-left","0");$("#allexams-row-scroll").parent(".sec-scroll-group").css("padding-right","0");}}}
function obtabscroll(direction){var container=document.getElementById('allexams-row-scroll');scrollCompleted=0;var slideVar=setInterval(function(){if(direction=='left'){container.scrollLeft-=30;}else{container.scrollLeft+=30;}
scrollCompleted+=30;if(scrollCompleted>=280){window.clearInterval(slideVar);}
var scrollwidth=$("#allexams-row-scroll").get(0).scrollWidth;var scrollleft=$("#allexams-row-scroll").scrollLeft();var elemwidth=$("#allexams-row-scroll").width();if(scrollleft<=0){$("#allexams-tabarrows-left").hide();}else{$("#allexams-tabarrows-left").css("display","flex");}
if(scrollwidth-scrollleft==elemwidth){$("#allexams-tabarrows-right").hide();}else{$("#allexams-tabarrows-right").css("display","flex");}},50);}
if($("#takefreemock-row-scroll").length){var scrollres=$("#takefreemock-row-scroll").hasScrollBar();if(ww>=992){if(scrollres){$("#takefreemock-tabarrows-right").css("display","flex");}else{$("#takefreemock-tabarrows-right").hide();$("#takefreemock-row-scroll").parent(".sec-scroll-group").css("padding-left","0");$("#takefreemock-row-scroll").parent(".sec-scroll-group").css("padding-right","0");}}}
function obtabscroll1(direction){var container=document.getElementById('takefreemock-row-scroll');scrollCompleted=0;var slideVar=setInterval(function(){if(direction=='left'){container.scrollLeft-=50;}else{container.scrollLeft+=50;}
scrollCompleted+=50;if(scrollCompleted>=320){window.clearInterval(slideVar);}
var scrollwidth=$("#takefreemock-row-scroll").get(0).scrollWidth;var scrollleft=$("#takefreemock-row-scroll").scrollLeft();var elemwidth=$("#takefreemock-row-scroll").width();if(scrollleft<=0){$("#takefreemock-tabarrows-left").hide();}else{$("#takefreemock-tabarrows-left").css("display","flex");}
if(scrollwidth-scrollleft==elemwidth){$("#takefreemock-tabarrows-right").hide();}else{$("#takefreemock-tabarrows-right").css("display","flex");}},50);}
if($("#todaylc-row-scroll").length){var scrollres=$("#todaylc-row-scroll").hasScrollBar();if(ww>=992){if(scrollres){$("#todaylc-tabarrows-right").css("display","flex");}else{$("#todaylc-tabarrows-right").hide();$("#todaylc-row-scroll").parent(".sec-scroll-group").css("padding-left","0");$("#todaylc-row-scroll").parent(".sec-scroll-group").css("padding-right","0");}}}
function obtabscroll2(direction){var container=document.getElementById('todaylc-row-scroll');scrollCompleted=0;var slideVar=setInterval(function(){if(direction=='left'){container.scrollLeft-=50;}else{container.scrollLeft+=50;}
scrollCompleted+=50;if(scrollCompleted>=320){window.clearInterval(slideVar);}
var scrollwidth=$("#todaylc-row-scroll").get(0).scrollWidth;var scrollleft=$("#todaylc-row-scroll").scrollLeft();var elemwidth=$("#todaylc-row-scroll").width();if(scrollleft<=0){$("#todaylc-tabarrows-left").hide();}else{$("#todaylc-tabarrows-left").css("display","flex");}
if(scrollwidth-scrollleft==elemwidth){$("#todaylc-tabarrows-right").hide();}else{$("#todaylc-tabarrows-right").css("display","flex");}},50);}
if($("#currentcourses-row-scroll").length){var scrollres=$("#currentcourses-row-scroll").hasScrollBar();if(ww>=992){if(scrollres){$("#currentcourses-tabarrows-right").css("display","flex");}else{$("#currentcourses-tabarrows-right").hide();$("#currentcourses-row-scroll").parent(".sec-scroll-group").css("padding-left","0");$("#currentcourses-row-scroll").parent(".sec-scroll-group").css("padding-right","0");}}}
function obtabscroll3(direction){var container=document.getElementById('currentcourses-row-scroll');scrollCompleted=0;var slideVar=setInterval(function(){if(direction=='left'){container.scrollLeft-=50;}else{container.scrollLeft+=50;}
scrollCompleted+=50;if(scrollCompleted>=320){window.clearInterval(slideVar);}
var scrollwidth=$("#currentcourses-row-scroll").get(0).scrollWidth;var scrollleft=$("#currentcourses-row-scroll").scrollLeft();var elemwidth=$("#currentcourses-row-scroll").width();if(scrollleft<=0){$("#currentcourses-tabarrows-left").hide();}else{$("#currentcourses-tabarrows-left").css("display","flex");}
if(scrollwidth-scrollleft==elemwidth){$("#currentcourses-tabarrows-right").hide();}else{$("#currentcourses-tabarrows-right").css("display","flex");}},50);}
function filtertabs(tabid){$(".obtab-item").removeClass("active");$(".exgall").hide();$("#obtab-item-"+tabid).addClass("active");$("#exams-group-"+tabid).show();}
$(document).on("click",".btn-viewmore",function(){$(this).parent(".sec-header-group").siblings(".togglecard-group").find(".togglecard").toggleClass("hide");if($(this).hasClass("in")){$(this).find(".txt-lessmore").html("View more");$(this).removeClass("in");}else{$(this).find(".txt-lessmore").html("View less");$(this).addClass("in");}});$(document).on("click",".btn-res-viewmore",function(){$(this).siblings(".togglecard-group").find(".togglecard").toggleClass("hide");if($(this).hasClass("in")){$(this).html("View more");$(this).removeClass("in");}else{$(this).html("View less");$(this).addClass("in");}});if((/Android|webOS|IEMobile|Opera Mini/i.test(navigator.userAgent))){if($('#open_app').length){$(".openinapp").css("display","flex");}}